<!DOCTYPE html>
<html lang="fr">
<head>
    
</head>
<body>
<article class="">
    <header>
        <h1>Nom et prénom de l'étudiant</h1>
    </header>
    <section>
        <h2>Notes : </h2>
        <ul>
            <li>Note 1</li>
            <li>Note 2</li>
            <li>Note 3</li>
        </ul>
    </section>
    <footer>
        <h3>Moyenne des notes de l'étudiant </h3>
    </footer>
</article>
</body>

</html>